package za.co.discovery.health.bigdata.ranger.feast;

import org.springframework.http.HttpMethod;

public enum Commands {
    GET_HEALTH(
        HttpMethod.GET,
        null,
        null
    ),
    GET_PROJECTS(
        HttpMethod.GET,
        null,
        null
    ),
    GET_RESOURCES(
        HttpMethod.GET,
        null,
        "read"
    ),
    TEARDOWN(
        HttpMethod.DELETE,
        null,
        "delete"
    ),
    POST_ENTITY(
        HttpMethod.POST,
        "entity",
        "modify_entity"
    ),
    DELETE_ENTITY(
        HttpMethod.DELETE,
        "entity",
        "delete_entity"
    ),
    GET_ENTITY(
        HttpMethod.GET,
        "entity",
        "get_entity"
    ),
    LIST_ENTITY(
        HttpMethod.GET,
        "entity",
        "list_entity"
    ),
    POST_DATA_SOURCE(
        HttpMethod.POST,
        "data_source",
        "modify_data_source"
    ),
    DELETE_DATA_SOURCE(
        HttpMethod.DELETE,
        "data_source",
        "delete_data_source"
    ),
    GET_DATA_SOURCE(
        HttpMethod.GET,
        "data_source",
        "get_data_source"
    ),
    LIST_DATA_SOURCE(
        HttpMethod.GET,
        "data_source",
        "list_data_source"
    ),
    POST_FEATURE_SERVICE(
        HttpMethod.POST,
        "feature_service",
        "modify_feature_service"
    ),
    DELETE_FEATURE_SERVICE(
        HttpMethod.DELETE,
        "feature_service",
        "delete_feature_service"
    ),
    GET_FEATURE_SERVICE(
        HttpMethod.GET,
        "feature_service",
        "get_feature_service"
    ),
    LIST_FEATURE_SERVICE(
        HttpMethod.GET,
        "feature_service",
        "list_feature_service"
    ),
    POST_FEATURE_VIEW(
        HttpMethod.POST,
        "feature_view",
        "modify_feature_view"
    ),
    DELETE_FEATURE_VIEW(
        HttpMethod.DELETE,
        "feature_view",
        "delete_feature_view"
    ),
    GET_FEATURE_VIEW(
        HttpMethod.GET,
        "feature_view",
        "get_feature_view"
    ),
    LIST_FEATURE_VIEW(
        HttpMethod.GET,
        "feature_view",
        "list_feature_view"
    ),
    POST_STREAM_FEATURE_VIEW(
        HttpMethod.POST,
        "stream_feature_view",
        "modify_stream_feature_view"
    ),
    GET_STREAM_FEATURE_VIEW(
        HttpMethod.GET,
        "stream_feature_view",
        "get_stream_feature_view"
    ),
    LIST_STREAM_FEATURE_VIEW(
        HttpMethod.GET,
        "stream_feature_view",
        "list_stream_feature_view"
    ),
    POST_ON_DEMAND_FEATURE_VIEW(
        HttpMethod.POST,
        "on_demand_feature_view",
        "modify_on_demand_feature_view"
    ),
    GET_ON_DEMAND_FEATURE_VIEW(
        HttpMethod.GET,
        "on_demand_feature_view",
        "get_on_demand_feature_view"
    ),
    LIST_ON_DEMAND_FEATURE_VIEW(
        HttpMethod.GET,
        "on_demand_feature_view",
        "list_on_demand_feature_view"
    ),
    POST_REQUEST_FEATURE_VIEW(
        HttpMethod.POST,
        "request_feature_view",
        "modify_request_feature_view"
    ),
    GET_REQUEST_FEATURE_VIEW(
        HttpMethod.GET,
        "request_feature_view",
        "get_request_feature_view"
    ),
    LIST_REQUEST_FEATURE_VIEW(
        HttpMethod.GET,
        "request_feature_view",
        "list_request_feature_view"
    ),
    POST_VALIDATION_REFERENCE(
        HttpMethod.POST,
        "validation_reference",
        "modify_validation_reference"
    ),
    DELETE_VALIDATION_REFERENCE(
        HttpMethod.DELETE,
        "validation_reference",
        "delete_validation_reference"
    ),
    GET_VALIDATION_REFERENCE(
        HttpMethod.GET,
        "validation_reference",
        "get_validation_reference"
    ),
    LIST_VALIDATION_REFERENCE(
        HttpMethod.GET,
        "validation_reference",
        "list_validation_reference"
    ),
    POST_SAVED_DATASET(
        HttpMethod.POST,
        "saved_dataset",
        "modify_saved_dataset"
    ),
    GET_SAVED_DATASET(
        HttpMethod.GET,
        "saved_dataset",
        "get_saved_dataset"
    ),
    LIST_SAVED_DATASET(
        HttpMethod.GET,
        "saved_dataset",
        "list_saved_dataset"
    ),
    POST_MANAGED_INFRA(
        HttpMethod.POST,
        "managed_infra",
        "modify_managed_infra"
    ),
    GET_MANAGED_INFRA(
        HttpMethod.GET,
        "managed_infra",
        "get_managed_infra"
    ),
    GET_FEAST_METADATA(
        HttpMethod.GET,
        "feast_metadata",
        "get_feast_metadata"
    ),
    POST_FEATURE_VIEW_USER_METADATA(
        HttpMethod.POST,
        "feature_view",
        "modify_feature_view_user_metadata"
    ),
    GET_FEATURE_VIEW_USER_METADATA(
        HttpMethod.GET,
        "feature_view",
        "get_feature_view_user_metadata"
    ),
    POST_STREAM_FEATURE_VIEW_USER_METADATA(
        HttpMethod.POST,
        "stream_feature_view",
        "modify_stream_feature_view_user_metadata"
    ),
    GET_STREAM_FEATURE_VIEW_USER_METADATA(
        HttpMethod.GET,
        "stream_feature_view",
        "get_stream_feature_view_user_metadata"
    ),
    POST_ON_DEMAND_FEATURE_VIEW_USER_METADATA(
        HttpMethod.POST,
        "on_demand_feature_view",
        "modify_on_demand_feature_view_user_metadata"
    ),
    GET_ON_DEMAND_FEATURE_VIEW_USER_METADATA(
        HttpMethod.GET,
        "on_demand_feature_view",
        "get_on_demand_feature_view_user_metadata"
    ),
    POST_REQUEST_FEATURE_VIEW_USER_METADATA(
        HttpMethod.POST,
        "request_feature_view",
        "modify_request_feature_view_user_metadata"
    ),
    GET_REQUEST_FEATURE_VIEW_USER_METADATA(
        HttpMethod.GET,
        "request_feature_view",
        "get_request_feature_view_user_metadata"
    );

    public final HttpMethod method;
    public final String resource;
    public final String accessType;
    Commands(
        HttpMethod method,
        ResourceEnum resource,
        String accessType
    ) {
        this.method = method;
        this.resource = resource;
        this.accessType = accessType; // null indicates no policy required
    }
}
